resources:
  - name: concourse_heartbeat
    type: git
    source: git@github.com:challiwill/concourse_heartbeat.git
    branch: master
    private_key: {{concourse_heartbeat-github-private-key}}
  - name: concourse_heartbeat-rc
    type: cf
    source: 
jobs:
  - name: unit
    plan:
      - get: concourse_heatbeat
        trigger: true
      - task: unit
        file: 
